[book]
authors = ["Blaž Hrastnik"]
language = "en"
multilingual = false
src = "src"

[output.html]
cname = "docs.rustcode-editor.com"
default-theme = "colibri"
preferred-dark-theme = "colibri"
git-repository-url = "https://github.com/rustcode-editor/rustcode"
edit-url-template = "https://github.com/rustcode-editor/rustcode/edit/master/book/{path}"
additional-css = ["custom.css"]

[output.html.search]
use-boolean-and = true
